version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: demo-postgres-14.2
    volumes:
      - medic_db_storage:/var/lib/postgresql/data
    command: 
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  web:
    build: .
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - web-app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3000:3000"
  
  # elasticsearch:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
  #  environment:
  #    - discovery.type=single-node
  #  ports:
  #    - 9200:9200
  #  volumes:
  #    - es_data:/usr/share/elasticsearch/data

volumes:
  medic_db_storage: {}
  web-app-storage: {}
  #es_data: {}